# Generated by Django 4.2.6 on 2023-11-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='made_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
